
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class form3 extends javax.swing.JFrame {


    /**
     * Creates new form form3
     */
    public form3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jpitant2 = new javax.swing.JTable();
        inser1 = new javax.swing.JButton();
        jTextId2 = new javax.swing.JTextField();
        jTextName2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextPhone2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextAge2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextEmail2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextDrId2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextDisease2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextGender2 = new javax.swing.JTextField();
        jBSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Welcome Dr. Ibrahim");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 273, 38));

        Jpitant2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "phone", "age", "e-mail", "gender", "the disease", "Dr_id"
            }
        ));
        Jpitant2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jpitant2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jpitant2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 60, 530, 92));

        inser1.setBackground(new java.awt.Color(102, 102, 0));
        inser1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        inser1.setForeground(new java.awt.Color(153, 0, 153));
        inser1.setText("Insert");
        inser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inser1ActionPerformed(evt);
            }
        });
        jPanel1.add(inser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 549, 92, 38));

        jTextId2.setEnabled(false);
        jTextId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextId2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 115, 33));
        jPanel1.add(jTextName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 218, 33));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 90, 33));
        jPanel1.add(jTextPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 218, 33));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 43, 31));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 62, 24));
        jPanel1.add(jTextAge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 218, 33));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 92, 31));
        jPanel1.add(jTextEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 218, 38));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 33));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type of Disease");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jTextDrId2.setEnabled(false);
        jPanel1.add(jTextDrId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 218, 33));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 549, 92, 38));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("modify");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 549, -1, 38));

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 85, 38));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dr_id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));
        jPanel1.add(jTextDisease2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 218, 33));

        jButton2.setText("print data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 23, 110, 30));
        jPanel1.add(jTextGender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 218, 29));

        jBSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSearch.setText("clinic statistics");
        jBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, 38));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tt.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inser1ActionPerformed
      this.setVisible(false);
        form5 f1 = new form5();
        f1.setVisible(true);

    }//GEN-LAST:event_inser1ActionPerformed

    private void jTextId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextId2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false);
        form1 f1 = new form1();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
            PreparedStatement stmt = con.prepareStatement("select * from patint where Doc_id = 2");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("id");
            dm.addColumn("name");
            dm.addColumn("age");
            dm.addColumn("gender");
            dm.addColumn("the disease");
            dm.addColumn("e-mail");
            dm.addColumn("phone");
            dm.addColumn("Dr.id");
            
            while (set.next()){
            String r[] = {set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8)};
                dm.addRow(r);
            }
            Jpitant2.setModel(dm);
            
        } catch (SQLException ex) {
            Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            

       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Jpitant2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpitant2MouseClicked
        // TODO add your handling code here:
        int row_num = Jpitant2.getSelectedRow();
         String id = Jpitant2.getValueAt(row_num, 0).toString();
         String name = Jpitant2.getValueAt(row_num, 1).toString();
         String age = Jpitant2.getValueAt(row_num, 2).toString();
         String gander = Jpitant2.getValueAt(row_num, 3).toString();
         String the_disease = Jpitant2.getValueAt(row_num, 4).toString();
         String email = Jpitant2.getValueAt(row_num, 5).toString();
         String phone = Jpitant2.getValueAt(row_num, 6).toString();
         String dr_id = Jpitant2.getValueAt(row_num, 7).toString();
         
         jTextId2.setText(id);
         jTextName2.setText(name);
         jTextAge2.setText(age);
         jTextPhone2.setText(phone);
         jTextEmail2.setText(email);
         jTextDisease2.setText(the_disease);
         jTextDrId2.setText(dr_id);
         jTextGender2.setText(gander);
    }//GEN-LAST:event_Jpitant2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
             PreparedStatement stmt = con.prepareStatement("update patint set Pat_name=?,Pat_age=?,Pat_disease=?,Pat_email=?,Pat_Phone_num=?,Doc_id=?,M_F_type=? where Pat_id=?" );
             String id = jTextId2.getText();
             String name = jTextName2.getText();
             String age = jTextAge2.getText();
             String the_disease = jTextDisease2.getText();
             String email = jTextEmail2.getText();
             String phone = jTextPhone2.getText();
             String dr_id = jTextDrId2.getText();
             String gander = jTextGender2.getText();
             stmt.setString(1, name);
             stmt.setString(2, age);
             stmt.setString(3, the_disease);
             stmt.setString(4, email);
             stmt.setString(5, phone);
             stmt.setString(6, dr_id);
             stmt.setString(7, gander);
             stmt.setString(8, id);
             stmt.executeUpdate();
             JOptionPane.showMessageDialog(this, "update success");
             jButton2ActionPerformed(evt);
             jTextName2.setText("");
             jTextAge2.setText("");
             jTextDisease2.setText("");
             jTextEmail2.setText("");
             jTextPhone2.setText("");
             jTextDrId2.setText("");
             jTextGender2.setText("");
             jTextId2.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
             PreparedStatement stmt = con.prepareStatement("delete from patint where Pat_id=?" );
             String id = jTextId2.getText();
             stmt.setString(1, id);
             stmt.executeUpdate();
             JOptionPane.showMessageDialog(this, "delete success");
             jButton2ActionPerformed(evt);
             jTextName2.setText("");
             jTextAge2.setText("");
             jTextDisease2.setText("");
             jTextEmail2.setText("");
             jTextPhone2.setText("");
             jTextDrId2.setText("");
             jTextGender2.setText("");
             jTextId2.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(form3.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSearchActionPerformed
        // TODO add your handling code here:
        

        form6 f1 = new form6();
        f1.setVisible(true);
    }//GEN-LAST:event_jBSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jpitant2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton inser1;
    private javax.swing.JButton jBSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAge2;
    private javax.swing.JTextField jTextDisease2;
    private javax.swing.JTextField jTextDrId2;
    private javax.swing.JTextField jTextEmail2;
    private javax.swing.JTextField jTextGender2;
    private javax.swing.JTextField jTextId2;
    private javax.swing.JTextField jTextName2;
    private javax.swing.JTextField jTextPhone2;
    // End of variables declaration//GEN-END:variables
}
