/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
import java.awt.event.ActionEvent;
import java.sql.*;  
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
public class form2 extends javax.swing.JFrame {

    
private String gender;
public static int numperPatDoc1;
    /**
     * Creates new form form2
     */
    public form2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jpitant1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextId1 = new javax.swing.JTextField();
        jTextName1 = new javax.swing.JTextField();
        jTextAge1 = new javax.swing.JTextField();
        jTextPhone1 = new javax.swing.JTextField();
        jTextDrId1 = new javax.swing.JTextField();
        jTextEmail1 = new javax.swing.JTextField();
        jTextDisease1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Jshow1 = new javax.swing.JButton();
        jTextGender1 = new javax.swing.JTextField();
        jBSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 83, 38));

        insert.setBackground(new java.awt.Color(102, 102, 0));
        insert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert.setForeground(new java.awt.Color(153, 0, 153));
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 92, 38));

        Jpitant1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "age", "gender", "the disease", "e-mail", "phone", "Dr_id"
            }
        ));
        Jpitant1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jpitant1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jpitant1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 549, 91));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Welcome Dr.Ahmed");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 259, 39));

        jButton7.setBackground(new java.awt.Color(102, 102, 0));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Modify");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, 38));

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 85, 38));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 43, 31));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 94, 41));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 92, 33));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 62, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 92, 41));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, 33));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Type of Disease");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 390, 130, -1));

        jTextId1.setEnabled(false);
        jTextId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextId1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 161, 92, 33));
        jPanel1.add(jTextName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 206, 207, 33));

        jTextAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAge1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 252, 207, 33));
        jPanel1.add(jTextPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 293, 207, 33));

        jTextDrId1.setEnabled(false);
        jPanel1.add(jTextDrId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 476, 207, 35));
        jPanel1.add(jTextEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 337, 207, 35));
        jPanel1.add(jTextDisease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 207, 35));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dr_id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 480, 50, -1));

        Jshow1.setBackground(new java.awt.Color(255, 204, 255));
        Jshow1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jshow1.setText("print data");
        Jshow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jshow1ActionPerformed(evt);
            }
        });
        jPanel1.add(Jshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 120, 40));
        jPanel1.add(jTextGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 207, 33));

        jBSearch.setBackground(new java.awt.Color(102, 102, 0));
        jBSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSearch.setText("clinic statistics");
        jBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, -1, 38));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tt.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
       this.setVisible(false);
        form4 f1 = new form4();
        f1.setVisible(true);
        
    }//GEN-LAST:event_insertActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        form1 f1 = new form1();
        f1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextId1ActionPerformed

    private void Jshow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jshow1ActionPerformed
                   Connection con;
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
        PreparedStatement stmt = con.prepareStatement("select * from patint where Doc_id = 1");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("id");
            dm.addColumn("name");
            dm.addColumn("age");
            dm.addColumn("gender");
            dm.addColumn("the disease");
            dm.addColumn("e-mail");
            dm.addColumn("phone");
            dm.addColumn("Dr.id");
            
            while (set.next()){
            String r[] = {set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7),set.getString(8)};
                dm.addRow(r);
            }
            
            Jpitant1.setModel(dm);
            numperPatDoc1=Jpitant1.getColumnCount() ;
    } catch (SQLException ex) {
        Logger.getLogger(form2.class.getName()).log(Level.SEVERE, null, ex);
    }
              
    }//GEN-LAST:event_Jshow1ActionPerformed

    private void Jpitant1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jpitant1MouseClicked
         // TODO add your handling code here:
         int row_num = Jpitant1.getSelectedRow();
         String id = Jpitant1.getValueAt(row_num, 0).toString();
         String name = Jpitant1.getValueAt(row_num, 1).toString();
         String age = Jpitant1.getValueAt(row_num, 2).toString();
         gender = Jpitant1.getValueAt(row_num, 3).toString();
         String the_disease = Jpitant1.getValueAt(row_num, 4).toString();
         String email = Jpitant1.getValueAt(row_num, 5).toString();
         String phone = Jpitant1.getValueAt(row_num, 6).toString();
         String dr_id = Jpitant1.getValueAt(row_num, 7).toString();
         
         jTextId1.setText(id);
         jTextName1.setText(name);
         jTextAge1.setText(age);
         jTextPhone1.setText(phone);
         jTextEmail1.setText(email);
         jTextDisease1.setText(the_disease);
         jTextDrId1.setText(dr_id);
         jTextGender1.setText(gender);
         
    }//GEN-LAST:event_Jpitant1MouseClicked

    private void jTextAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAge1ActionPerformed
        gender = "mail";
    }//GEN-LAST:event_jTextAge1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
             PreparedStatement stmt = con.prepareStatement("update patint set Pat_name=?,Pat_age=?,Pat_disease=?,Pat_email=?,Pat_Phone_num=?,Doc_id=?,M_F_type=? where Pat_id=?" );
             String id = jTextId1.getText();
             String name = jTextName1.getText();
             String age = jTextAge1.getText();
             String the_disease = jTextDisease1.getText();
             String email = jTextEmail1.getText();
             String phone = jTextPhone1.getText();
             String dr_id = jTextDrId1.getText();
             String gander = jTextGender1.getText();
             stmt.setString(1, name);
             stmt.setString(2, age);
             stmt.setString(3, the_disease);
             stmt.setString(4, email);
             stmt.setString(5, phone);
             stmt.setString(6, dr_id);
             stmt.setString(7, gander);
             stmt.setString(8, id);
             stmt.executeUpdate();
             JOptionPane.showMessageDialog(this, "update success");
             Jshow1ActionPerformed(evt);
             jTextName1.setText("");
             jTextAge1.setText("");
             jTextDisease1.setText("");
             jTextEmail1.setText("");
             jTextPhone1.setText("");
             jTextDrId1.setText("");
             jTextGender1.setText("");
             jTextId1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(form2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinic", "root", "root");
             PreparedStatement stmt = con.prepareStatement("delete from patint where Pat_id=?" );
             String id = jTextId1.getText();
             stmt.setString(1, id);
             stmt.executeUpdate();
             JOptionPane.showMessageDialog(this, "delete success");
             Jshow1ActionPerformed(evt);
             jTextName1.setText("");
             jTextAge1.setText("");
             jTextDisease1.setText("");
             jTextEmail1.setText("");
             jTextPhone1.setText("");
             jTextDrId1.setText("");
             jTextGender1.setText("");
             jTextId1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(form2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSearchActionPerformed
        // TODO add your handling code here:
        
        
        form6 f1 = new form6();
        f1.setVisible(true);
    }//GEN-LAST:event_jBSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Jpitant1;
    private javax.swing.JButton Jshow1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton insert;
    private javax.swing.JButton jBSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAge1;
    private javax.swing.JTextField jTextDisease1;
    private javax.swing.JTextField jTextDrId1;
    private javax.swing.JTextField jTextEmail1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextGender1;
    private javax.swing.JTextField jTextId1;
    private javax.swing.JTextField jTextName1;
    private javax.swing.JTextField jTextPhone1;
    // End of variables declaration//GEN-END:variables
}
